prettyblocks_layout_presets:
  path: /modules/prettyblocks/layout_presets/
  methods: [GET,POST]
  defaults:
    _controller: 'PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController::getLayoutPresetsAction'
    _legacy_controller: AdminLayoutPresetController
    _legacy_link: AdminLayoutPresetController

prettyblocks_layout_presets_save:
  path: /modules/prettyblocks/layout_presets/save
  methods: [POST]
  defaults:
    _controller: 'PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController::saveLayoutPresetAction'

prettyblocks_layout_presets_preview:
  path: /modules/prettyblocks/layout_presets/preview
  methods: [POST]
  defaults:
    _controller: 'PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController::previewLayoutPresetAction'

prettyblocks_layout_presets_confirm:
  path: /modules/prettyblocks/layout_presets/confirm
  methods: [POST]
  defaults:
    _controller: 'PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController::confirmLayoutPreviewAction'

prettyblocks_layout_presets_cancel:
  path: /modules/prettyblocks/layout_presets/cancel
  methods: [POST]
  defaults:
    _controller: 'PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController::cancelLayoutPreviewAction'
