services:
    prettyblocks.command.release:
        class: PrestaSafe\PrettyBlocks\Command\ReleaseCommand
        tags:
            - { name: 'console.command' }

    PrestaSafe\PrettyBlocks\Controller\AdminThemeManagerController:
        class: PrestaSafe\PrettyBlocks\Controller\AdminThemeManagerController
        public: true
        parent: prestashop.core.admin.controller

    PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController:
        class: PrestaSafe\PrettyBlocks\Controller\AdminLayoutPresetController
        public: true
        parent: prestashop.core.admin.controller

